### ISSUE TITLE
An inherited reference that is further type-constrained in a child is shown as the type, not a reference

### ISSUE THREAD

**Issue by jgibson** [standardhealth/shr-json-javadoc#1]
When a parent class has a value that is a reference and then a child class constrains it the doc view shows the type instead of the reference. For an example see `Patient`. The value of `Role` is `ref(Party)` and the value of `Patient` is `ref(Person)`, however it is shown as `Person`: http://standardhealthrecord.org/reference-model/shr-entity/Patient.html

In addition the patient entry also does not indicate that value was further constrained from the parent class (although that may be an unrelated problem).

**Comment by Abhijay** [comment]
See: https://abhijay.github.io/reference-model/shr-entity/Patient.html for fixed page
